<?php

namespace Database\Seeders;

use App\Models\Plante;
use Illuminate\Database\Seeder;

class PlanteSeeder extends Seeder
{
    public function run(): void
    {
        $plantes = [
            [
                'nom' => 'Tomate',
                'espece' => 'Solanum lycopersicum',
                'famille' => 'Solanacées',
                'origine' => 'Amérique du Sud',
                'description' => 'Légume-fruit très cultivé au Maroc, adapté aux régions chaudes. Riche en lycopène et vitamine C.',
                'conditionsCulture' => 'Sol bien drainé, riche en matière organique. pH 6.0–6.8. Exposition plein soleil. Arrosage régulier sans excès.',
                'temperatureMin' => 10,
                'temperatureMax' => 35,
                'saisonPlantation' => 'printemps',
                'dureePousseeJours' => 75,
                'rendementMoyenKgHa' => 60000,
                'typeIrrigation' => 'goutte_a_goutte',
                'estBio' => false,
                'imageUrl' => 'https://images.unsplash.com/photo-1546094096-0df4bcaaa337?w=600',
            ],
            [
                'nom' => 'Blé dur',
                'espece' => 'Triticum durum',
                'famille' => 'Graminées',
                'origine' => 'Moyen-Orient',
                'description' => 'Céréale principale du Maroc, base de la semoule et du couscous. Très résistant à la sécheresse.',
                'conditionsCulture' => 'Sol argileux ou limoneux. pH 6.0–7.5. Semis en automne. Résistant au froid hivernal.',
                'temperatureMin' => 3,
                'temperatureMax' => 32,
                'saisonPlantation' => 'automne',
                'dureePousseeJours' => 150,
                'rendementMoyenKgHa' => 3500,
                'typeIrrigation' => 'pluviale',
                'estBio' => false,
                'imageUrl' => 'https://images.unsplash.com/photo-1574323347407-f5e1ad6d020b?w=600',
            ],
            [
                'nom' => 'Olivier',
                'espece' => 'Olea europaea',
                'famille' => 'Oléacées',
                'origine' => 'Bassin méditerranéen',
                'description' => 'Arbre emblématique du Maroc. Produit des olives pour l\'huile et la table. Très longévif et résistant.',
                'conditionsCulture' => 'Sol calcaire bien drainé. pH 6.5–8.5. Résistant à la sécheresse. Taille annuelle recommandée.',
                'temperatureMin' => -5,
                'temperatureMax' => 40,
                'saisonPlantation' => 'printemps',
                'dureePousseeJours' => 1460,
                'rendementMoyenKgHa' => 8000,
                'typeIrrigation' => 'goutte_a_goutte',
                'estBio' => true,
                'imageUrl' => 'https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?w=600',
            ],
            [
                'nom' => 'Arganier',
                'espece' => 'Argania spinosa',
                'famille' => 'Sapotacées',
                'origine' => 'Maroc (endémique)',
                'description' => 'Arbre endémique du Maroc, classé patrimoine mondial UNESCO. Produit l\'huile d\'argan précieuse.',
                'conditionsCulture' => 'Sol aride et rocailleux. Résistant à la sécheresse extrême. Région du Souss-Massa.',
                'temperatureMin' => 5,
                'temperatureMax' => 45,
                'saisonPlantation' => 'automne',
                'dureePousseeJours' => 2555,
                'rendementMoyenKgHa' => 500,
                'typeIrrigation' => 'pluviale',
                'estBio' => true,
                'imageUrl' => 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600',
            ],
            [
                'nom' => 'Clémentine',
                'espece' => 'Citrus clementina',
                'famille' => 'Rutacées',
                'origine' => 'Algérie / Maroc',
                'description' => 'Agrume phare du Maroc, exporté dans le monde entier. Riche en vitamine C. Récolte de novembre à janvier.',
                'conditionsCulture' => 'Sol limoneux bien drainé. pH 6.0–7.0. Irrigation régulière. Région du Gharb et Souss.',
                'temperatureMin' => 5,
                'temperatureMax' => 38,
                'saisonPlantation' => 'printemps',
                'dureePousseeJours' => 270,
                'rendementMoyenKgHa' => 25000,
                'typeIrrigation' => 'goutte_a_goutte',
                'estBio' => false,
                'imageUrl' => 'https://images.unsplash.com/photo-1611080626919-7cf5a9dbab12?w=600',
            ],
            [
                'nom' => 'Pomme de terre',
                'espece' => 'Solanum tuberosum',
                'famille' => 'Solanacées',
                'origine' => 'Andes (Pérou)',
                'description' => 'Tubercule très cultivé au Maroc, notamment dans le Gharb et le Saïss. Deux cycles par an possibles.',
                'conditionsCulture' => 'Sol meuble, profond et bien drainé. pH 5.5–6.5. Éviter l\'excès d\'humidité pour prévenir le mildiou.',
                'temperatureMin' => 7,
                'temperatureMax' => 25,
                'saisonPlantation' => 'printemps',
                'dureePousseeJours' => 90,
                'rendementMoyenKgHa' => 25000,
                'typeIrrigation' => 'aspersion',
                'estBio' => false,
                'imageUrl' => 'https://images.unsplash.com/photo-1518977676601-b53f82aba655?w=600',
            ],
            [
                'nom' => 'Menthe poivrée',
                'espece' => 'Mentha piperita',
                'famille' => 'Lamiacées',
                'origine' => 'Europe',
                'description' => 'Herbe aromatique incontournable au Maroc pour le thé à la menthe. Cultivation facile et rentable.',
                'conditionsCulture' => 'Sol humide et riche. Mi-ombre ou plein soleil. Arrosage fréquent. Multiplication par stolons.',
                'temperatureMin' => 5,
                'temperatureMax' => 30,
                'saisonPlantation' => 'printemps',
                'dureePousseeJours' => 60,
                'rendementMoyenKgHa' => 15000,
                'typeIrrigation' => 'aspersion',
                'estBio' => true,
                'imageUrl' => 'https://images.unsplash.com/photo-1628556270448-4d4e4148e1b1?w=600',
            ],
            [
                'nom' => 'Cactus figuier de Barbarie',
                'espece' => 'Opuntia ficus-indica',
                'famille' => 'Cactacées',
                'origine' => 'Mexique',
                'description' => 'Très répandu au Maroc. Fruits comestibles riches en antioxydants. Huile de pépins très valorisée.',
                'conditionsCulture' => 'Sol pauvre et sec. Résistant à la sécheresse. Peu d\'entretien. Régions arides et semi-arides.',
                'temperatureMin' => 0,
                'temperatureMax' => 45,
                'saisonPlantation' => 'printemps',
                'dureePousseeJours' => 365,
                'rendementMoyenKgHa' => 20000,
                'typeIrrigation' => 'pluviale',
                'estBio' => true,
                'imageUrl' => 'https://images.unsplash.com/photo-1459411552884-841db9b3cc2a?w=600',
            ],
            [
                'nom' => 'Oignon',
                'espece' => 'Allium cepa',
                'famille' => 'Amaryllidacées',
                'origine' => 'Asie centrale',
                'description' => 'Légume de base de la cuisine marocaine. Cultivé dans tout le pays, exporté vers l\'Europe.',
                'conditionsCulture' => 'Sol léger et bien drainé. pH 6.0–7.0. Semis en automne pour récolte au printemps.',
                'temperatureMin' => 5,
                'temperatureMax' => 30,
                'saisonPlantation' => 'automne',
                'dureePousseeJours' => 120,
                'rendementMoyenKgHa' => 30000,
                'typeIrrigation' => 'goutte_a_goutte',
                'estBio' => false,
                'imageUrl' => 'https://images.unsplash.com/photo-1508747703725-719777637510?w=600',
            ],
            [
                'nom' => 'Safran',
                'espece' => 'Crocus sativus',
                'famille' => 'Iridacées',
                'origine' => 'Grèce / Iran',
                'description' => 'L\'or rouge du Maroc. Cultivé principalement à Taliouine (Souss). Épice la plus chère au monde.',
                'conditionsCulture' => 'Sol calcaire bien drainé. Altitude 1500–2000m. Plantation en été, floraison en octobre-novembre.',
                'temperatureMin' => -5,
                'temperatureMax' => 35,
                'saisonPlantation' => 'été',
                'dureePousseeJours' => 90,
                'rendementMoyenKgHa' => 6,
                'typeIrrigation' => 'goutte_a_goutte',
                'estBio' => true,
                'imageUrl' => 'https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=600',
            ],
            [
                'nom' => 'Pastèque',
                'espece' => 'Citrullus lanatus',
                'famille' => 'Cucurbitacées',
                'origine' => 'Afrique tropicale',
                'description' => 'Très cultivée dans le Souss et le Gharb. Fruit d\'été par excellence, grande demande locale et export.',
                'conditionsCulture' => 'Sol sableux bien drainé. Chaleur et soleil indispensables. Arrosage contrôlé à la floraison.',
                'temperatureMin' => 18,
                'temperatureMax' => 40,
                'saisonPlantation' => 'printemps',
                'dureePousseeJours' => 85,
                'rendementMoyenKgHa' => 35000,
                'typeIrrigation' => 'goutte_a_goutte',
                'estBio' => false,
                'imageUrl' => 'https://images.unsplash.com/photo-1587049352846-4a222e784d38?w=600',
            ],
            [
                'nom' => 'Dattier',
                'espece' => 'Phoenix dactylifera',
                'famille' => 'Arécacées',
                'origine' => 'Moyen-Orient / Afrique du Nord',
                'description' => 'Palmier emblématique des oasis marocaines (Drâa, Tafilalet). Dattes Medjool parmi les meilleures au monde.',
                'conditionsCulture' => 'Sol sableux profond. Chaleur intense nécessaire. Irrigation régulière. Pollinisation manuelle recommandée.',
                'temperatureMin' => 0,
                'temperatureMax' => 50,
                'saisonPlantation' => 'printemps',
                'dureePousseeJours' => 200,
                'rendementMoyenKgHa' => 10000,
                'typeIrrigation' => 'submersion',
                'estBio' => true,
                'imageUrl' => 'https://images.unsplash.com/photo-1601493700631-2b16ec4b4716?w=600',
            ],
        ];

        foreach ($plantes as $data) {
            Plante::firstOrCreate(['nom' => $data['nom']], $data);
        }
    }
}
