<?php
namespace Database\Seeders;
use App\Models\Plante;
use Illuminate\Database\Seeder;
class PlanteSeeder extends Seeder
{
    public function run(): void
    {
        $plantes = [
            [
                'nom' => 'Tomate',
                'espece' => 'Solanum lycopersicum',
                'famille' => 'Solanacées',
                'origine' => 'Amérique du Sud',
                'description' => 'Culture exigeante à fort besoin en potasse (K) et calcium. Sensible au mildiou (Phytophthora infestans) et à l\'alternariose. Nécessite un tuteurage dès 30 cm. Espacement recommandé : 50 cm sur le rang, 1 m entre rangs.',
                'conditionsCulture' => 'Sol bien drainé, riche en matière organique. pH 6.0–6.8. Exposition plein soleil. Arrosage régulier sans excès.',
                'temperatureMin' => 10,
                'temperatureMax' => 35,
                'saisonPlantation' => 'printemps',
                'dureePousseeJours' => 75,
                'rendementMoyenKgHa' => 60000,
                'typeIrrigation' => 'goutte_a_goutte',
                'estBio' => false,
                'besoin_eau_l_m2' => 6.3,
                'imageUrl' => '/images/plantes/tomate.webp',
            ],
            [
                'nom' => 'Blé dur',
                'espece' => 'Triticum durum',
                'famille' => 'Graminées',
                'origine' => 'Moyen-Orient',
                'description' => 'Céréale à paille à cycle long. Sensible à la rouille jaune (Puccinia striiformis) et à la septoriose. Densité de semis : 180–220 kg/ha. Apport azoté fractionné recommandé (tallage + montaison).',
                'conditionsCulture' => 'Sol argileux ou limoneux. pH 6.0–7.5. Semis en automne. Résistant au froid hivernal.',
                'temperatureMin' => 3,
                'temperatureMax' => 32,
                'saisonPlantation' => 'automne',
                'dureePousseeJours' => 150,
                'rendementMoyenKgHa' => 3500,
                'typeIrrigation' => 'pluviale',
                'estBio' => false,
                'besoin_eau_l_m2' => 6.3,
                'imageUrl' => '/images/plantes/ble-dur.webp',
            ],
            [
                'nom' => 'Olivier',
                'espece' => 'Olea europaea',
                'famille' => 'Oléacées',
                'origine' => 'Bassin méditerranéen',
                'description' => 'Arbre pérenne à entrée en production tardive (4–5 ans). Sensible à la mouche de l\'olive (Bactrocera oleae) et à l\'œil de paon (Spilocaea oleagina). Taille de fructification annuelle obligatoire. Densité : 100–200 arbres/ha.',
                'conditionsCulture' => 'Sol calcaire bien drainé. pH 6.5–8.5. Résistant à la sécheresse. Taille annuelle recommandée.',
                'temperatureMin' => -5,
                'temperatureMax' => 40,
                'saisonPlantation' => 'printemps',
                'dureePousseeJours' => 1460,
                'rendementMoyenKgHa' => 8000,
                'typeIrrigation' => 'goutte_a_goutte',
                'estBio' => true,
                'besoin_eau_l_m2' => 3.6,
                'imageUrl' => '/images/plantes/olivier.webp',
            ],
            [
                'nom' => 'Arganier',
                'espece' => 'Argania spinosa',
                'famille' => 'Sapotacées',
                'origine' => 'Maroc (endémique)',
                'description' => 'Espèce endémique à croissance très lente (production à 7–10 ans). Résistance xérophytique exceptionnelle. Pas de traitement phytosanitaire conventionnel. Densité : 100 arbres/ha max. Récolte manuelle des fruits uniquement.',
                'conditionsCulture' => 'Sol aride et rocailleux. Résistant à la sécheresse extrême. Région du Souss-Massa.',
                'temperatureMin' => 5,
                'temperatureMax' => 45,
                'saisonPlantation' => 'automne',
                'dureePousseeJours' => 2555,
                'rendementMoyenKgHa' => 500,
                'typeIrrigation' => 'pluviale',
                'estBio' => true,
                'besoin_eau_l_m2' => 3.0,
                'imageUrl' => '/images/plantes/arganier.webp',
            ],
            [
                'nom' => 'Clémentine',
                'espece' => 'Citrus clementina',
                'famille' => 'Rutacées',
                'origine' => 'Algérie / Maroc',
                'description' => 'Agrume sensible au Phytophthora (pourriture du collet) et à la tristeza (CTV). Greffage sur Citrange Carrizo recommandé. Besoins élevés en azote (N) et magnésium (Mg). Éclaircissage chimique ou manuel pour calibre export.',
                'conditionsCulture' => 'Sol limoneux bien drainé. pH 6.0–7.0. Irrigation régulière. Région du Gharb et Souss.',
                'temperatureMin' => 5,
                'temperatureMax' => 38,
                'saisonPlantation' => 'printemps',
                'dureePousseeJours' => 270,
                'rendementMoyenKgHa' => 25000,
                'typeIrrigation' => 'goutte_a_goutte',
                'estBio' => false,
                'besoin_eau_l_m2' => 3.9,
                'imageUrl' => '/images/plantes/clementine.webp',
            ],
            [
                'nom' => 'Pomme de terre',
                'espece' => 'Solanum tuberosum',
                'famille' => 'Solanacées',
                'origine' => 'Andes (Pérou)',
                'description' => 'Culture à fort risque mildiou (Phytophthora infestans) en conditions humides. Utiliser des semences certifiées. Buttage obligatoire à 20–25 cm de hauteur. Besoins élevés en potasse (K2O : 200–250 kg/ha). Espacement : 30 cm sur rang.',
                'conditionsCulture' => 'Sol meuble, profond et bien drainé. pH 5.5–6.5. Éviter l\'excès d\'humidité pour prévenir le mildiou.',
                'temperatureMin' => 7,
                'temperatureMax' => 25,
                'saisonPlantation' => 'printemps',
                'dureePousseeJours' => 90,
                'rendementMoyenKgHa' => 25000,
                'typeIrrigation' => 'aspersion',
                'estBio' => false,
                'besoin_eau_l_m2' => 6.3,
                'imageUrl' => '/images/plantes/pomme-de-terre.webp',
            ],
            [
                'nom' => 'Menthe poivrée',
                'espece' => 'Mentha piperita',
                'famille' => 'Lamiacées',
                'origine' => 'Europe',
                'description' => 'Multiplication végétative par stolons ou rhizomes exclusivement. Sensible à la rouille (Puccinia menthae). Récolte avant floraison pour maximiser la teneur en menthol. 3–4 coupes par an possibles. Rotation obligatoire tous les 3 ans.',
                'conditionsCulture' => 'Sol humide et riche. Mi-ombre ou plein soleil. Arrosage fréquent. Multiplication par stolons.',
                'temperatureMin' => 5,
                'temperatureMax' => 30,
                'saisonPlantation' => 'printemps',
                'dureePousseeJours' => 60,
                'rendementMoyenKgHa' => 15000,
                'typeIrrigation' => 'aspersion',
                'estBio' => true,
                'besoin_eau_l_m2' => 5.5,
                'imageUrl' => '/images/plantes/menthe-poivree.webp',
            ],
            [
                'nom' => 'Cactus figuier de Barbarie',
                'espece' => 'Opuntia ficus-indica',
                'famille' => 'Cactacées',
                'origine' => 'Mexique',
                'description' => 'Plantation par cladodes (raquettes) de 2 ans minimum. Espacement : 5 m × 5 m (400 pieds/ha). Sensible à la cochenille farineuse (Dactylopius opuntiae). Pas de fertilisation azotée excessive. Rendement stabilisé à partir de la 3e année.',
                'conditionsCulture' => 'Sol pauvre et sec. Résistant à la sécheresse. Peu d\'entretien. Régions arides et semi-arides.',
                'temperatureMin' => 0,
                'temperatureMax' => 45,
                'saisonPlantation' => 'printemps',
                'dureePousseeJours' => 365,
                'rendementMoyenKgHa' => 20000,
                'typeIrrigation' => 'pluviale',
                'estBio' => true,
                'besoin_eau_l_m2' => 1.7,
                'imageUrl' => '/images/plantes/cactus-figuier.webp',
            ],
            [
                'nom' => 'Oignon',
                'espece' => 'Allium cepa',
                'famille' => 'Amaryllidacées',
                'origine' => 'Asie centrale',
                'description' => 'Culture sensible au mildiou (Peronospora destructor) et à la fusariose. Densité : 400 000–600 000 plants/ha. Arrêt de l\'irrigation 2–3 semaines avant récolte pour favoriser la maturation des bulbes. Besoins en soufre (S) importants.',
                'conditionsCulture' => 'Sol léger et bien drainé. pH 6.0–7.0. Semis en automne pour récolte au printemps.',
                'temperatureMin' => 5,
                'temperatureMax' => 30,
                'saisonPlantation' => 'automne',
                'dureePousseeJours' => 120,
                'rendementMoyenKgHa' => 30000,
                'typeIrrigation' => 'goutte_a_goutte',
                'estBio' => false,
                'besoin_eau_l_m2' => 5.8,
                'imageUrl' => '/images/plantes/oignon.webp',
            ],
            [
                'nom' => 'Safran',
                'espece' => 'Crocus sativus',
                'famille' => 'Iridacées',
                'origine' => 'Grèce / Iran',
                'description' => 'Plantation de cormes (calibre ≥ 8 cm). Densité : 50–80 cormes/m². Récolte manuelle des stigmates à l\'aube, uniquement en octobre-novembre. Sensible à la pourriture des cormes (Fusarium oxysporum). Rotation tous les 7–8 ans obligatoire.',
                'conditionsCulture' => 'Sol calcaire bien drainé. Altitude 1500–2000m. Plantation en été, floraison en octobre-novembre.',
                'temperatureMin' => -5,
                'temperatureMax' => 35,
                'saisonPlantation' => 'été',
                'dureePousseeJours' => 90,
                'rendementMoyenKgHa' => 6,
                'typeIrrigation' => 'goutte_a_goutte',
                'estBio' => true,
                'besoin_eau_l_m2' => 3.6,
                'imageUrl' => '/images/plantes/safran.webp',
            ],
            [
                'nom' => 'Pastèque',
                'espece' => 'Citrullus lanatus',
                'famille' => 'Cucurbitacées',
                'origine' => 'Afrique tropicale',
                'description' => 'Culture sensible à l\'anthracnose et au fusarium du collet. Greffage sur porte-greffe Cucurbita recommandé en sol infesté. Espacement : 2 m × 1 m. Pollinisation entomophile indispensable. Réduction de l\'irrigation à la véraison pour améliorer le taux de sucre (Brix).',
                'conditionsCulture' => 'Sol sableux bien drainé. Chaleur et soleil indispensables. Arrosage contrôlé à la floraison.',
                'temperatureMin' => 18,
                'temperatureMax' => 40,
                'saisonPlantation' => 'printemps',
                'dureePousseeJours' => 85,
                'rendementMoyenKgHa' => 35000,
                'typeIrrigation' => 'goutte_a_goutte',
                'estBio' => false,
                'besoin_eau_l_m2' => 5.5,
                'imageUrl' => '/images/plantes/pasteque.webp',
            ],
            [
                'nom' => 'Dattier',
                'espece' => 'Phoenix dactylifera',
                'famille' => 'Arécacées',
                'origine' => 'Moyen-Orient / Afrique du Nord',
                'description' => 'Palmier dioïque nécessitant une pollinisation manuelle (1 mâle pour 25–50 femelles). Sensible au Bayoud (Fusarium oxysporum f.sp. albedinis). Éclaircissage des régimes obligatoire pour calibre Medjool. Production commerciale à partir de 5–8 ans. Densité : 100–160 palmiers/ha.',
                'conditionsCulture' => 'Sol sableux profond. Chaleur intense nécessaire. Irrigation régulière. Pollinisation manuelle recommandée.',
                'temperatureMin' => 0,
                'temperatureMax' => 50,
                'saisonPlantation' => 'printemps',
                'dureePousseeJours' => 200,
                'rendementMoyenKgHa' => 10000,
                'typeIrrigation' => 'submersion',
                'estBio' => true,
                'besoin_eau_l_m2' => 5.2,
                'imageUrl' => '/images/plantes/dattier.webp',
            ],
        ];
        foreach ($plantes as $data) {
            Plante::firstOrCreate(['nom' => $data['nom']], $data);
        }
    }
}
